### ISSUE TITLE
Simplify install and dependency management

### ISSUE THREAD

**Issue by Guideon72** [Rwright7/ImageExifRemover#1]
Create 'requirements.txt' in root of the project:

- Open command prompt in your directory
- run 'python -m pip freeze -r requirements.txt
- 
This will make a new file in that directory that contains all of the versions of your required libraries
https://pip.pypa.io/en/stable/cli/pip_freeze/

Then, when anyone including yourself, clones or downloads this project, they can use a one line cli command to take care of installing the expected version of those libs.  

- Open command prompt in your project root
- run 'python -m pip install requirements.txt'

Just make sure Python is installed on the system first; and, if using virtual environments, that the venv is active at the command prompt before running the command.
https://pip.pypa.io/en/stable/cli/pip_install/

**Comment by Rwright7** [comment]
Completed
