### ISSUE TITLE
Possibly missed error handling

### ISSUE THREAD

**Issue by Guideon72** [Rwright7/ImageExifRemover#2]
Lines 19 - 22:
	def extract_data(self, image_path:str) -> dict:
		if not os.path.exists(image_path):
			return None

simply returns None instead of giving a nice notification the way 44 - 47 do:
	def remove_data(self, image_path: str) -> bool:
		if not os.path.exists(image_path):
			print(f"'{image_path}' does not exists!")
			return False

**Comment by Rwright7** [comment]
Completed
