### ISSUE TITLE
Change print() statements to return statements

### ISSUE THREAD

**Issue by Guideon72** [Rwright7/ImageExifRemover#3]
Since you are applying a GUI over the top of this, it would be a good idea to convert the print() statements that are part of your functional returns (differentiating from your error handling prints()).
Since prints() only output to the command line, you or the user will never see notifications like

		if not os.path.exists(image_path):
			print(f"'{image_path}' does not exists!")
			return False
becomes

		if not os.path.exists(image_path):
                        notfound_msg = f"'{image_path}' does not exists!"
			return notfound_msg

Then refactor the handling in your UI to replicate that basic notification rather than making a notification in both base and upper level files.
Other option, if you want to keep the print statements for cli use, you *can* use both:

		if not os.path.exists(image_path):
                        notfound_msg = f"'{image_path}' does not exists!"
                        print(notfound_msg) #realistically, these should be converted over to Logging rather than print()s
			return notfound_msg

**Comment by Rwright7** [comment]
what about the code below, wouldn't that yield the same results as you have ? 
def remove_data(self, image_path: str) -> str:
    if not os.path.exists(image_path):
        return f"'{image_path}' does not exist!"


also I'm looking into logging in python, there is a module for it.

**Comment by Guideon72** [comment]
Sort of.  Print() and return are different mechanisms that are important to understand the difference between.  
Print() takes a string object and writes it out to the standard output for Python, which is the terminal window; this is the only place that text will be visible.  
Return takes whatever object is specified (or a None type object if no other type is defined) and passes that object back to the process or function that called it.

So, in this case, the remove_data function would not print anything to the console itself; it would simply return a string object to the point in your main code where the function was called, and you would have to actually do something with it there in order to use or see that value.

I highly, HIGHLY recommend not hard-coding anything that you do not need to, also.  In this case, for example, you are using that message for error handling in 2, different functions.  If, in the future, you were to need or want to re-write or otherwise modify that statement, you will have to do it in two places and pay attention to make sure you modify both the same.
If you define the message in a variable, you can re-use it multiple places, but only have to maintain a single line; which is what I did in that last example.  Used notfound_msg for both the print statement and return value, but only had to write it once.

**Comment by Rwright7** [comment]
I understand. I changed it in both places. 

so extract_data is now
```def extract_data(self, image_path:str) -> dict:
		if not os.path.exists(image_path):
			notfound_msg = f"'{image_path}' does not exists!"
		return notfound_msg
 ```

and remove_data is now 
```
def remove_data(self, image_path: str) -> bool:
		if not os.path.exists(image_path):
			notfound_msg = f"'{image_path}' does not exists!"
		return notfound_msg
```

**Comment by Rwright7** [comment]
complete
