### ISSUE TITLE
Consider making ExifTag instanced

### ISSUE THREAD

**Issue by Guideon72** [Rwright7/ImageExifRemover#5]
ExifTag is fine as a simple class; however, it's likely to give you some fits if you decide to enhance the app to handle multiple images.

class ExifTag:
        ....

to

class ExifTag:
        def __init__(self, image_path:str) > None
            self.image_path = image_path
        ....

If you do this, just remember to review your image_path params in each class method and update to self.image_path. :)

**Comment by Rwright7** [comment]
Complete
