### ISSUE TITLE
Consider refactoring file path strings to be actual Python objects using Path instead of OS

### ISSUE THREAD

**Issue by Guideon72** [Rwright7/ImageExifRemover#6]
With more recent versions of Python, the pathlib module has gained popularity/preference for building and using file paths.  One of the biggest gains from this is that you no longer have to worry about whether you're using the correct string format if moving between Unix/Windows (i.e forward slash (/) vs backslash (\).

Basic example:
    from pathlib import Path

    fpath = Path('C', 'Users', '<username>', 'MyDocuments')
    print(fpath)

    OUTPUT: C:\Users\<username>\MyDocuments
    
Path is a subclass of the higher level Path objects that will build concrete paths, based on the OS the script is run on; so, you don't have to explicitly handle that.  Making this more portable, amongst other things.
It will also make setting file paths as variables and parameters much cleaner to read at the sacrifice of a couple of extra lines.

**Comment by Rwright7** [comment]
I changed the following 
```
new_image_path = os.path.join(os.getcwd(), 'newphoto.jpg')
```
to 
```
new_image_path = self.image_path.parent / "newphoto.jpg"
```

Also should I do it for that snippet below

```
if not os.path.exists(self.image_path):
			notfound_msg = f"'{self.image_path}' does not exists!"
```

it would then change to 

```
if not self.image_path.exists():
            notfound_msg = f"'{self.image_path}' does not exist!"
            return notfound_msg
```
